import {
  resturant,
  DrivingSchools,
  PetShop,
  rent,
  beautySpa,
  constructor,
  constructorpackersMovers,
  consultants,
  courierService,
  dentist,
  education,
  estateAgent,
  gym,
  homeDecore,
  hospitalEventOrganizers,
  hotel,
  pgHostels,
  weddingRequisitos,
} from "@/assets";

export const INITIAL_CURRENT_USER_DATA = {
  id: "",
  email: "",
  name: "",
  roles: [""],
};

export const INITIAL_AUTH_CONTEXT = {
  currentUser: null,
  setCurrentUser: () => {},
};

export const INITIAL_DATA_CONTEXT = {
  currentUserData: null,
  setCurrentUserData: () => {},
  sectionAdds: null,
  sectionStaticAdds: null,
  sliderAdds: null,
  popularBrands: null,
  searchResultStores: null,
  setSearchResultStores: () => {},
  searchItem: "",
  setSearchitem: () => {},
  location: "",
  setLocation: () => {},
  loadingStoreFetching: false,
  setLoadingStoreFetching: () => {},
  lastDocument: null,
  setLastDocument: () => {},
  isAllFetched: false,
  setIsAllFetched: () => {},
  userMessages: null,
  locationArr: null,
  setLocationArr: () => {},
};

export const INITIAL_SCHEDULAR_ARR = [
  { day: "Monday", time: ["08:00", "05:00"] },
  { day: "Tuesday", time: ["08:00", "05:00"] },
  { day: "Wednesday", time: ["08:00", "05:00"] },
  { day: "Thursday", time: ["08:00", "05:00"] },
  { day: "Friday", time: ["08:00", "05:00"] },
  { day: "Saturday", time: ["08:00", "05:00"] },
  { day: "Sunday", time: ["08:00", "05:00"] },
];

export const categories = [
  { icon: resturant, label: "Resrurant" },
  { icon: hotel, label: "Hotel" },
  { icon: beautySpa, label: "Beauty Spa" },
  { icon: homeDecore, label: "Home Decore" },
  { icon: weddingRequisitos, label: "Wedding Requisitos" },
  { icon: education, label: "Education" },
  { icon: rent, label: "Rent" },
  { icon: pgHostels, label: "PG Hostels" },
  { icon: estateAgent, label: "Estate Agent" },
  { icon: dentist, label: "Dentist" },
  { icon: gym, label: "Gym" },
  { icon: consultants, label: "Consultants" },
  { icon: hospitalEventOrganizers, label: "Hospital" },
  { icon: DrivingSchools, label: "Driving Schools" },
  { icon: constructorpackersMovers, label: "Constructor" },
  { icon: PetShop, label: "Pet Shop" },
  { icon: courierService, label: "Courier Service" },
  { icon: constructor, label: "Constructor" },
];


export const popularCategories = [
  "Body Massage Centers",
  "Cinema Halls",
  "Schools",
  "Beauty Spas",
  "Dermatologists",
  "Hospitals",
  "Malls",
  "Gyms",
  "Beauty Parlours",
  "Estate Agents",
  "Banquet Halls",
  "ENT Doctors",
  "Book Shops",
  "Bike On Rent",
  "Sexologist Doctors",
  "Neurologists",
  "Gynaecologist & Obstetrician Doctors",
  "Train Ticket Booking Agents",
  "Travel Agents",
  "Paying Guest Accommodations",
  "General Physician Doctors",
  "Dentists",
  "Orthopaedic Doctors",
  "Chemists",
  "Motor Training Schools",
  "Gastroenterologists",
  "Car Rental",
  "Salons",
  "Courier Services",
  "Dance Classes",
  "Pathology Labs",
  "Taxi Services",
  "Cake Shops",
  "AC Repair & Services",
  "Mobile Phone Dealers",
  "Pet Shops",
  "Dmart",
  "Packers And Movers",
  "Psychiatrists",
  "Dharamshalas",
  "Urologist Doctors",
  "Bakeries",
  "Bicycle Dealers",
  "Coffee Shops",
  "Paediatricians",
  "Sonography Centres",
  "Yoga Classes",
  "Hostels",
  "Cardiologists",
  "Electrical Shops",
  "Skin Care Clinics",
  "Diagnostic Centres",
  "Homeopathic Doctors",
  "Physiotherapists",
  "Photo Studios",
  "Plumbers",
  "Music Classes",
  "Electricians",
  "Sports Goods Dealers",
  "Shoe Dealers",
  "Hair Stylists",
  "Gift Shops",
  "Ophthalmologists",
  "Car Repair & Services",
  "Ayurvedic Doctors",
  "Eye Clinics",
  "Restaurants",
  "Carpenters",
  "Jewellery Showrooms",
  "Cooks On Hire",
  "Stationery Shops",
  "Nephrologists",
  "Caterers",
  "Interior Designers",
  "Rehabilitation Center",
  "Drug De Addiction Center",
  "Grocery Stores",
  "Banks",
  "ATM",
  "5Star Hotels",
  "Hotels",
  "Resorts",
  "Plastic Surgeons",
];

export const popularCities = [
  "Akkaraipattu",
  "Ampara",
  "Anuradhapura",
  "Badulla",
  "Balangoda",
  "Bandarawela",
  "Batticaloa",
  "Chavakachcheri",
  "Chilaw",
  "Colombo",
  "Dambulla",
  "Dehiwela-Mount Lavinia",
  "Embilipitiya",
  "Eravur",
  "Galle",
  "Gampaha",
  "Gampola",
  "Hambantota",
  "Happutalle",
  "Homagama",
  "Jaffna",
  "Kalmunai",
  "Kalutara",
  "Kandy",
  "Kattankudy",
  "Kegalle",
  "Kinniya",
  "Kurunegala",
  "Kuliyapitiya",
  "Mahiyanganaya",
  "Mannar",
  "Matale",
  "Matara",
  "Mawathagama",
  "Mihintale",
  "Monaragala",
  "Mulleriyawa",
  "Negombo",
  "Nuwara Eliya",
  "Padukka",
  "Puttalam",
  "Polonnaruwa",
  "Point Pedro",
  "Ratnapura",
  "Sri Jayewardenepura Kotte",
  "Thambiluvil",
  "Trincomalee",
  "Valvettithurai",
  "Vavuniya",
  "Vijitapura",
];
